
lego_model_path: demo1.ldr

environment:
  # Travel height for the robot arm.
  travel_height: 0.15  # Meters
  simulated: False

network:
  host:  # PC running the main program
    ip: 192.168.1.78
    port: 9001

  ur:  # Is set in the UR controller's network setup panel.
      ip: 192.168.1.198
      port: 30002  # Secondary client port is 30002

  raspi:  # Server running on the Raspberry Pi
    ip: 192.168.1.218
    port: 9002


#camera:
#  resolution:
#    x: 1200
#    y: 800


bricks:
  # HSV color ranges for bricks, e.g. from [0, 100, 100] to [10, 255, 255]
  # Each subkey (e.g. 1 and 2) defines a single continuous range and one color may
  # consist of multiple ranges. Multi ranges are combined using OR operation.
  # Max values [180, 255, 255].
  colors:
    green:
      1:
        - [60, 150, 4]
        - [85, 255, 70]
    red:
      1:
       - [0, 115, 25]
       - [5, 255, 145]
      2:
       - [175, 115, 25]
       - [180, 255, 145]
    yellow:
      1:
        - [10, 155, 85]
        - [25, 255, 205]
    blue:
      1:
        - [100, 75, 10]
        - [120, 255, 135]


grip_def_script: legoassembler/urscripts/gripper_def_robotiq-2f-85.script

calibration_data:
  camera: camera_calibr.yml
  platform: platform_calibr.yml