
lego_model_path: demo1.ldr

environment:
  # Travel height for the robot arm.
  travel_height: 0.15  # Meters
  simulated: False

network:
  host:  # PC running the main program
    ip: 192.168.1.78
    port: 9001

  ur:  # Is set in the UR controller's network setup panel.
      ip: 192.168.1.198
      port: 30002  # Secondary client port is 30002

  raspi:  # Server running on the Raspberry Pi
    ip: 192.168.1.218
    port: 9002


#camera:
#  resolution:
#    x: 1200
#    y: 800


bricks:
  # HSV color ranges for bricks, e.g. from [0, 100, 100] to [10, 255, 255]
  # Each subkey (e.g. 1 and 2) defines a single continuous range and one color may
  # consist of multiple ranges. Multi ranges are combined using OR operation.
  # Max values [180, 255, 255].
  colors:
    light_green:
      1:
        - [53, 40, 28]
        - [80, 255, 255]
    red:
      1:
       - [0, 115, 85]
       - [7, 255, 215]
      2:
       - [175, 115, 85]
       - [180, 255, 215]
    yellow:
      1:
        #- [11, 115, 145]
        #- [28, 255, 255]
        - [53, 40, 28]  # actually green
        - [80, 255, 255]
    blue:
      1:
        - [100, 115, 45]
        - [120, 255, 200]


grip_def_script: legoassembler/urscripts/gripper_def_robotiq-2f-85.script

calibration_data:
  camera: camera_calibr.yml
  platform: platform_calibr.yml