

environment:
  # Travel height for the robot arm.
  travel_height: 0.3  # Meters

network:
  host:  # PC running the main program
    ip: 192.168.1.78
    port: 9001

  ur:  # Is set in the UR controller's network setup panel.
      ip: 192.168.1.198
      port: 30002  # Secondary client port is 30002

  raspi:  # Server running on the Raspberry Pi
    ip: 192.168.1.218
    port: 9002


camera:
  resolution:
    x: 1200
    y: 800


bricks:
  # HSV color ranges for bricks, e.g. from [0, 100, 100] to [10, 255, 255]
  # Max values [180, 255, 255].
  colors:
    green:
      - [55, 100, 8]
      - [85, 255, 133]
    red:
      - [0, 150, 40]
      - [5, 255, 141]
    yellow:
      - [10, 150, 70]
      - [25, 255, 205]
    blue:
      - [100, 150, 10]
      - [120, 255, 105]

ur_scripts:
  directory: urscripts
  build: build.script
  preview: build_preview.script
  calibrate_camera: calibrate_camera.script
  teach_platform: teach_platform.script
  preview_taught_platform: preview_taught_platform.script
  gripper_urcap_preamble: gripper_urcap_preamble.script
  gripper_function_definition: gripper_function_definition.script
  test_camera_calibration: test_camera_calibration.script

calibration_data:
  camera: camera_calibr.yml
  platform: platform_calibr.yml