
lego_model_path: demo1.ldr

environment:
  # Travel height for the robot arm.
  travel_height: 0.15  # Meters
  simulated: False

network:
  host:  # PC running the main program
    ip: 192.168.1.78
    port: 9001

  ur:  # Is set in the UR controller's network setup panel.
      ip: 192.168.1.198
      port: 30002  # Secondary client port is 30002

  raspi:  # Server running on the Raspberry Pi
    ip: 192.168.1.218
    port: 9002

brick_2x2_length: 31.8

grip_def_script: legoassembler/urscripts/gripper_def_robotiq-2f-85.script

calibration_data:
  camera: camera_calibr.yml
  platform: platform_calibr.yml
  colors: color_definitions.yml